# Generated by Django 5.2.8 on 2025-12-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('Quantity', models.IntegerField()),
                ('expiry_hours', models.IntegerField()),
                ('expiry_at', models.DateTimeField(blank=True, null=True)),
                ('Address', models.TextField()),
                ('District', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=10)),
                ('people_can_feed', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
